name: Bug Report
description: File a bug report.
title: '[Bug]'

body:
  - type: textarea
    attributes:
      label: Description of the Bug
      description: What's the issue you encountered?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: How can the issue be reproduced?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What do you expect to happen?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Notes
      description: Add any other notes or screenshots about the bug here.
    validations:
      required: false
